"""add pickup time in stop node

Revision ID: 00470f37531d
Revises: 24951b47b762
Create Date: 2025-12-31 11:58:49.885019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00470f37531d'
down_revision: Union[str, Sequence[str], None] = '24951b47b762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_stop_nodes', sa.Column('pickup_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_stop_nodes', 'pickup_time')
    # ### end Alembic commands ###
