"""Add category to Event model

Revision ID: 08f7e6e08ba2
Revises: ac45f29e65a3
Create Date: 2025-12-30 12:55:06.354677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f7e6e08ba2'
down_revision: Union[str, Sequence[str], None] = 'ac45f29e65a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'category')
    # ### end Alembic commands ###
