"""Add SharedInventory model

Revision ID: 24951b47b762
Revises: 08f7e6e08ba2
Create Date: 2025-12-30 14:12:02.941392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24951b47b762'
down_revision: Union[str, Sequence[str], None] = '08f7e6e08ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_stop_nodes', sa.Column('shared_inventory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event_stop_nodes', 'shared_inventories', ['shared_inventory_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_stop_nodes', type_='foreignkey')
    op.drop_column('event_stop_nodes', 'shared_inventory_id')
    # ### end Alembic commands ###
