"""create event routes and stop nodes

Revision ID: ac45f29e65a3
Revises: 604fba33fb2d
Create Date: 2025-12-29 16:48:18.452783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac45f29e65a3'
down_revision: Union[str, Sequence[str], None] = '604fba33fb2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_day_id', sa.Integer(), nullable=False),
    sa.Column('route_template_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_location', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_day_id'], ['event_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_routes_event_day_id'), 'event_routes', ['event_day_id'], unique=False)
    op.create_index(op.f('ix_event_routes_name'), 'event_routes', ['name'], unique=False)
    op.create_table('event_stop_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('booking_capacity', sa.Integer(), nullable=True),
    sa.Column('next_stop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_stop_id'], ['event_stop_nodes.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['event_routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_stop_nodes')
    op.drop_index(op.f('ix_event_routes_name'), table_name='event_routes')
    op.drop_index(op.f('ix_event_routes_event_day_id'), table_name='event_routes')
    op.drop_table('event_routes')
    # ### end Alembic commands ###
