"""added group_id in route model

Revision ID: bb48149e34cd
Revises: 604fba33fb2d
Create Date: 2025-12-25 19:19:03.037274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb48149e34cd'
down_revision: Union[str, Sequence[str], None] = '604fba33fb2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_routes', sa.Column('group_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_routes', 'group_id')
    # ### end Alembic commands ###
